#!/bin/sh
#
# monitor_access_log.sh
#
# Arguments: [<tail_argument1>, ...] -- [<ignore_regex1>, ...]
#
source `dirname $(realpath "$0")`/standingbear.sh

##
#
#
filter_vhost_combined () {
    return
}

#exec tail -f "$StandingBear/var/log/"{error_log,access_log,php.log} | ( `which ccze >2 /dev/null` && ccze -A || cat )
exec tail -f "$StandingBear/var/log/"*log | ( [ "x`which ccze 2> /dev/null`" != "x" ] && ccze -A || cat )
